config/routes.rb
Rails.application.routes.draw do
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :topics

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }


  resources :portfolios do
    resources :examples
    put :sort, on: :collection
  end

 

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy
  has_many :examples, dependent: :destroy
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }



  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
    where(subtitle: 'Angular')
  end

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :show, :update, :destroy]
  layout 'portfolio'
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all, editor: :all
  
  def index
      @portfolio_items = Portfolio.by_position
      @page_title = "IC-MN Team"
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Dein Profil ist nun zu sehen.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Dein Profil wurde aktualisiert' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @page_title = "IC-MN Team"
  end

  def destroy
    # Destroy/delete the record
    @portfolio_item.destroy

    # Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Dein Profil wurde gelöscht' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy]
                                     )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

require 'uri'

  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end

  def image_title(msg)

    uri_title =  p URI.split(msg)[5]
    title = uri_title.split("/").last.split(".").first.gsub("-", " ").gsub("_", " ")

  end


end

app/views/portfolios/_display_example_fotos.html.erb
<div class="card-columns">
 <% example_item.images.shift %>
 <% example_item.images.each do |image| %>
   <div class="card">
   	 <img src="<%= image.url(:medium).to_s %>" class="card-img-top" alt="<%= image_title(image.to_s) %>">
   </div>
 <% end %>
</div>

app/views/portfolios/_display_fotos.html.erb
<div>
  <% if @portfolio_item.main_image? %>
  <label>Hauptbild:</label>
  <%= image_tag @portfolio_item.main_image, height: '80px' %> 
  <% end %>

  <% if @portfolio_item.thumb_image? %>

  <label>Platzhalter:</label>
  <%= image_tag @portfolio_item.thumb_image, height: '80px' %>
  <% end %>
</div>

app/views/portfolios/_example_item.html.erb
 <% if example_item.images.present? %>
  <%= image_tag example_item.images[0].url(:large).to_s, class: "img-fluid" %>
 <% end %>

 <h1><%= example_item.title %></h1>

  <% if  example_item.audio.present? %>
    <audio controls>
    <source src="<%= example_item.audio.url %>" type="audio/mpeg">Audio</audio><br>
  <% end %>

 <p><%= markdown example_item.body %></p>

 <%= render 'display_example_fotos', example_item: example_item %>

 <% if login_checker %>
  <div class="">
  <%= link_to "Beitrag bearbeiten", edit_portfolio_example_path(example_item.portfolio, example_item), class: 'btn btn-warning' %>
  <%= link_to "Beitrag löschen", portfolio_example_path(example_item.portfolio, example_item), method: :delete, data: { confirm: 'Willst du deinen Beitrag wirklich löschen? Dann sind auch die Bilder weg...' }, class: 'btn btn-danger'  %>
  </div><br />
<% end %>
<hr />

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error, class: 'alert-message' %>
    <% end %>
  <% end %>
  
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :motto %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload Hauptbild <%= f.file_field :main_image, style: 'display:none;' %>
        </label>
        <label class="btn btn-primary">
          Upload Platzhalter Foto <%= f.file_field :thumb_image, style: 'display:none;' %>
        </label>
      <div>
      <%= render 'display_fotos' %>
     </div>
    </div>
  </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :beschreibung %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h2>Qualifikationen:</h2>
    <div>
      <%= f.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>

      <div>
        <%= link_to_add_association 'Qualifikation hinzufügen', f, :technologies %>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit 'Speichern', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card portfolio-box" data-id="<%= portfolio_item.id %>">
    <div class='image-fluid'>
    <a href='<%= portfolio_show_path(portfolio_item) %>'>
      <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'), width: '100%' %>
    </a>
    <p class="card-text">
      <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> <%= portfolio_item.subtitle %>
    </p>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Qualifikation entfernen', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Team Mitglieder</h1>

<%= link_to "Neues Team Mitglied", new_portfolio_url if login_checker %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Profil Bearbeiten", edit_portfolio_path(portfolio_item) if login_checker %>
  <%= link_to 'Löschen', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Bist du sicher?' } if login_checker %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Bearbeite Team Mitglied</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container-fluid">
    <%= source_helper("alert alert-warning") %>

    <div class="row"> 

    <% if login_checker %>
        <div class="col-12">
          <%= link_to "Neues Team Mitglied anlegen", new_portfolio_path, class: 'btn btn-primary' %>
        </div>
      <% end %>
    
    </div>

    <hr>

    <div class="row <%= "sortable" if login_checker %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Neues Team Mitglied anlegen</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>  
</div>

app/views/portfolios/show.html.erb
<div class="container-fluid portfolio-container">
  <div class="row">


    <div class="col-md-7 image-fluid">
       <p> <%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '50%' %></p>
       <br />

        <div class="">
          <%= link_to "Neuen Beispielbeitrag erstellen", new_portfolio_example_path(@portfolio_item), class: 'btn btn-primary' if login_checker %>
        </div><br />
        
      <% @portfolio_item.examples.each do |example| %>
        <%= render 'example_item', example_item: example %>
      <% end %>
    </div>  



    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>

      <hr>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%= @portfolio_item.body %></p>

      <hr>

      <h3>Qualifikationen:</h3>

      <% @portfolio_item.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>

      <% if login_checker %>
        <div class="">
          <%= link_to "Profil Bearbeiten", edit_portfolio_path(@portfolio_item), class: 'btn btn-primary' %>
          <%= link_to "Profil Löschen", portfolio_path(@portfolio_item), method: :delete, data: { confirm: 'Willst du dein Profil wirklich löschen? Dann sind auch die Bilder weg...' }, class: 'btn btn-danger'  %>
        </div>
      <% end %>

    
    </div>
  </div>
</div>